theme: jekyll-theme-minimal
title: Custom Portfolio
description: This site is a custom portfolio website aiming to showcase *abilities, talents, creativity* and *learning* that the author implements in the subsequent detailed projects available on the site.